#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Salih√úLKER - Resume
url: "https://styraist.github.io/online-cv/"

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv'

description: As a highly motivated and dynamic professional, I stand out for my passion for innovation and my commitment to pursuing excellence. With a diverse skill set and a proven track record of delivering results, I perform best in fast-paced environments where creativity meets strategy. With a commitment to continuous learning while paying special attention to detail, I am ready to make meaningful contributions to any team by boldly taking on challenges.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: turquoise # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
